
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\12244\Desktop\Git\itms448-groupproject\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("900x600")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 600,
    width = 900,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    466.0,
    270.0,
    image=image_image_1
)

canvas.create_text(
    52.0,
    254.0,
    anchor="nw",
    text="Log In",
    fill="#000000",
    font=("IstokWeb Regular", 48 * -1)
)


#username entry
entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    160.5,
    375.5,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=53.0,
    y=358.0,
    width=217.0,
    height=33.0
)

#username label
canvas.create_text(
    52.0,
    341.0,
    anchor="nw",
    text="Username",
    fill="#000000",
    font=("IstokWeb Regular", 12 * -1)
)


#password entry
entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    160.5,
    438.5,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=53.0,
    y=421.0,
    width=217.0,
    height=33.0
)

#password text
canvas.create_text(
    52.0,
    404.0,
    anchor="nw",
    text="Password",
    fill="#000000",
    font=("IstokWeb Regular", 12 * -1)
)

#submit button and hover Effects
submitButton = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=submitButton,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"), #CHANGE THIS COMMAND TO SWITCH TO NEXT WINDOW
    relief="flat"
)
button_1.place(
    x=116.0,
    y=486.0,
    width=89.0,
    height=25.0
)

buttonHover_1 = PhotoImage(
    file=relative_to_assets("button_hover_1.png"))

def button_1_hover(e):
    button_1.config(
        image=buttonHover_1
    )
def button_1_leave(e):
    button_1.config(
        image=submitButton
    )

#hover effect in action
button_1.bind('<Enter>', button_1_hover)
button_1.bind('<Leave>', button_1_leave)


#perma code
window.resizable(False, False)
window.mainloop()
